import React, { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { DatabaseZap, RefreshCw, ShieldAlert, ShieldCheck } from "lucide-react";
import { useAuth } from "../auth-context";
import { Badge, Button, Card, Spinner } from "../components/ui";
import { connectMockSource, getDataSources, getDouyinStatus, requestDouyinAuthorization, syncMockSource } from "../lib/api";

const stateName = { not_connected: "待连接", connected: "已连接", synced: "同步成功", error: "同步失败" };

export default function SourcesPage() {
  const { isAdmin } = useAuth();
  const client = useQueryClient();
  const [notice, setNotice] = useState("");
  const sources = useQuery({ queryKey: ["data-sources"], queryFn: getDataSources });
  const official = useQuery({ queryKey: ["douyin-status"], queryFn: getDouyinStatus });
  const connect = useMutation({ mutationFn: connectMockSource, onSuccess: (result) => { client.invalidateQueries({ queryKey: ["data-sources"] }); setNotice(`${result.data.label}已连接到本地模拟数据集`); } });
  const sync = useMutation({ mutationFn: syncMockSource, onSuccess: (result) => { client.invalidateQueries(); setNotice(`${result.data.label}同步完成：${result.data.record_count} 条有效记录`); }, onError: (error) => { client.invalidateQueries({ queryKey: ["data-sources"] }); setNotice(error.response?.data?.detail || "同步失败"); } });
  const authorize = useMutation({ mutationFn: requestDouyinAuthorization, onError: (error) => setNotice(error.response?.data?.detail || "当前无法发起正式授权") });
  return <div className="content"><div className="page-intro"><div><p className="eyebrow">DATA SOURCE CONTROL</p><h2>数据源接入</h2><p className="muted">分别管理商品与热点来源，先在本机验证连接、同步和数据质量。</p></div><Badge tone="gray">本地 Demo · 零抖音真实请求</Badge></div>{notice && <div className="source-notice" role="status">{notice}</div>}<div className="source-grid">{sources.isLoading ? <div className="loading"><Spinner /></div> : sources.isError ? <p className="form-error">无法读取模拟数据源状态。</p> : sources.data?.data.map((source) => <Card className="source-card" key={source.resource}><div className="source-head"><span className="source-icon"><DatabaseZap size={19} /></span><Badge tone={source.status === "synced" ? "green" : "gray"}>{stateName[source.status]}</Badge></div><h3>{source.label}</h3><p className="muted">本地 JSON 模拟数据 · {source.resource === "products" ? "商品池" : "趋势热点"}</p><dl className="source-facts"><div><dt>来源模式</dt><dd>mock / 离线</dd></div><div><dt>有效记录</dt><dd>{source.record_count ?? "—"}</dd></div><div><dt>拒绝记录</dt><dd>{source.rejected_count ?? "—"}</dd></div><div><dt>最近同步</dt><dd>{source.last_success_at ? new Date(source.last_success_at).toLocaleString("zh-CN") : "尚未同步"}</dd></div><div><dt>快照 ID</dt><dd>{source.snapshot_id || "—"}</dd></div></dl>{source.last_error && <p className="form-error">{source.last_error}</p>}<div className="source-actions"><Button variant="secondary" onClick={() => connect.mutate(source.resource)} disabled={!isAdmin || source.connected || connect.isPending}>{connect.isPending && connect.variables === source.resource ? <Spinner /> : <ShieldCheck size={14} />}连接模拟数据</Button><Button onClick={() => sync.mutate(source.resource)} disabled={!isAdmin || !source.connected || sync.isPending}>{sync.isPending && sync.variables === source.resource ? <Spinner /> : <RefreshCw size={14} />}立即同步</Button></div>{!isAdmin && <small className="muted">仅管理员可以连接和同步。</small>}</Card>)}</div><Card className="official-card"><div className="section-heading"><div><p className="eyebrow">PRODUCTION INTEGRATION</p><h3>抖音官方 API 接入入口</h3></div><Badge tone="gray">待开通</Badge></div><p className="muted">{official.data?.data?.message || "正在确认接入条件…"}</p><div className="official-resources">{official.data?.data?.resources?.map((resource) => <div key={resource.resource}><strong>{resource.label}</strong><span>独立申请授权与接口权限</span><Badge tone="gray">待审批</Badge></div>)}</div><div className="official-checklist"><h4><ShieldAlert size={16} />正式接入前置条件</h4><ol>{official.data?.data?.prerequisites?.map((item) => <li key={item}>{item}</li>)}</ol></div><div className="official-bottom"><p>此入口仅展示正式接入流程；Demo 不采集 AppSecret / Access Token，也不会向抖音发送请求。</p><Button variant="secondary" onClick={() => authorize.mutate()} disabled={!isAdmin || authorize.isPending}>{authorize.isPending ? <Spinner /> : <ShieldCheck size={14} />}检查正式授权入口</Button></div></Card></div>;
}
